#include<stdio.h>
#include<stdbool.h>
int main(){
    int integervalue=10;
    float floatvalue=5.55f;
    long longvalue=12345l;
    char charvalue='A';
    long long longlongvalue=12345678910ll;
    double doublevalue=3.124567;
    char stringvalue= 'H';
    printf("\n__Variable Fundamental__");
    printf("\n integer:%d",integervalue);
    printf("\n float :%f",floatvalue);
    printf("\nlong:%ld",longvalue);
    printf("\nchar:%c",charvalue);
    printf("\nlong long:%lld",longlongvalue);
    printf("\ndouble:%lf",doublevalue);
    printf("\nstring:%s",stringvalue);
    printf("\nNew integer value:");
    scanf("\n%d",&integervalue);
    printf("\nYou Entered New Integer Value");
    int a=5,b=6;
    printf("\n__Arithmatic Operator__");
    printf("\naddition:%d",a+b);
    printf("\nsubstrsction:%d",a-b);
    printf("\nmultiply:%d",a*b);
    printf("\ndivision:%d",a/b);
    printf("\nmodulo:%d",a%b);
    int A=10,B=15;
    bool truevalue=true;
    bool falsevalue=false;
    printf("\n__Relational Operator__");
    printf("\ntrue represent:%d",truevalue);
    printf("\nfalse represent:%d",falsevalue);
    printf("\nequalto:%d",A==B);
    printf("\nnot equalto:%d",A!=B);
    printf("\ngreater than:%d",A>B);
    printf("\nless than:%d",A<B);
    printf("\ngreater than or equal to:%d",A>=B);
    printf("\nless than or equal to:%d",A<=B);
    printf("\nlogical AND:%d",truevalue&&falsevalue);
    printf("\nlogical OR:%d",truevalue||falsevalue);
    printf("\nlogical NOT:%d",!truevalue);
    int num=10;
    printf("\n__Initial Operator__");
    printf("\ninitial num:%d",num);
    printf("\npost_incriment:%d",num++);
    printf("\nafter post_incriment:%d",num);
    printf("\npre_incriment:%d",++num);
    printf("\nDecriment:%d",num--);
    int Assignvalue=13;
    int REassignvalue=10;
    printf("\n__Assignment Operator__");
    printf("\nnew value in add:%d",Assignvalue+=REassignvalue);
    printf("\nnew value in subs:%d",Assignvalue-=REassignvalue);
    printf("\nnew value in multi:%d",Assignvalue*=REassignvalue);
    printf("\nnew value in divi:%d",Assignvalue/=REassignvalue);
    printf("\nnew value in modulo:%d",Assignvalue%=REassignvalue);
    return 0;
}